version: '3.1'

services:
  appliances:
    build: ./appliances
    container_name: appliances
    ports:
      - 8081:3000
    expose:
      - 8081
    volumes:
      - ./appliances/src:/home/app/src
    command: npm run start

  auth:
    build: ./auth
    container_name: auth
    ports:
     - 3000:3000
    volumes: 
     - ./auth/src:/home/app/src
    command: npm run start

  client:
    container_name: client
    volumes:
     - ../client/src:/home/app/src
    build:
      context: ../client
      dockerfile: ../client/Dockerfile
    ports:
     - 3006:3000
    command: npm run start

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8080:8080
    links:
      - appliances
